name: ILP-Radio-Array-3.10
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.7.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - gflags=2.2.2
  - glog=0.7.1
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.5.0
  - libutf8proc=2.10.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=17.0.6
  - lz4-c=1.10.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - ncurses=6.4
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - openjpeg=2.5.0
  - openssl=3.5.2
  - orc=2.2.0
  - packaging=24.2
  - pillow=9.4.0
  - pip=25.1
  - prometheus-cpp=1.3.0
  - pthread-stubs=0.4
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pyparsing=3.2.0
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python_abi=3.10
  - re2=2025.07.22
  - readline=8.2
  - setuptools=72.1.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.45.2
  - tk=8.6.13
  - tornado=6.5.1
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - appdirs==1.4.4
      - asciitree==0.3.3
      - astroplan==0.10.1
      - astropy==6.1.7
      - astropy-healpix==1.1.2
      - astropy-iers-data==0.2025.7.7.0.39.39
      - attrs==25.3.0
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - dask==2025.5.1
      - ducc0==0.36.0
      - fasteners==0.19
      - filelock==3.18.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gurobipy==12.0.2
      - h5py==3.14.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - locket==1.0.0
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - numcodecs==0.13.1
      - numpy==1.26.4
      - overrides==7.7.0
      - pandas==2.3.1
      - partd==1.4.2
      - photutils==1.13.0
      - prettytable==3.16.0
      - pulp==3.2.1
      - pyerfa==2.0.1.5
      - pyfftw==0.15.0
      - python-gitlab==3.15.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - reproject==0.14.1
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rpds-py==0.26.0
      - schema==0.7.7
      - scipy==1.15.3
      - ska-ost-array-config==4.0.1
      - ska-sdp-datamodels==1.0.0
      - ska-sdp-func-python==1.0.0
      - ska-telmodel==1.23.0
      - smmap==5.0.2
      - tomli==2.2.1
      - toolz==0.12.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - xarray==2024.10.0
      - zarr==2.18.3
      - zipp==3.23.0
